### ISSUE TITLE
Wrong folder Rights with RH 8.6 and mariadb

### ISSUE THREAD

**Issue by Kotty666** [markt-de/puppet-galera#182]
We are using RedHat 8.6 and the logfolder Creation (/var/log/mariadb) wokrs but the folder is created for root:root with 0700 so mariaDB is not able to store there files.

**Comment by fraenki** [comment]
Unfortunately still not reproducable for me. This may be related to a local security configuration (selinux? something else?). If someone can provide steps to make this reproducable, please let me know. I'll close this issue now.
