### ISSUE TITLE
binlog_format drop from default data breaks Galera-Node service restart

### ISSUE THREAD

**Issue by TwizzyDizzy** [markt-de/puppet-galera#190]
Hi folks,

In 1fcae22f3b5e5553045ef7eb2b456fb135fa8e85, `binlog_format: 'ROW'` has been dropped from data, stating that **binlog_format** has been deprecated. As of today, I cannot find such information for MariaDB (e.g. neither [here](https://mariadb.com/kb/en/binary-log-formats/) nor [there](https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#binlog_format)).

Only thing I can find is [this](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_format) information on MySQL:
> binlog_format is deprecated as of MySQL 8.0.34, and is subject to removal in a future version of MySQL. This implies that support for logging formats other than row-based is also subject to removal in a future release. Thus, only row-based logging should be employed for any new MySQL Replication setups.

The result for this is (at least as just tested on my end with `10.11.7`):
```
Apr 15 13:36:40 HOSTNAME sh[646241]: WSREP: Failed to start mysqld for wsrep recovery: '2024-04-15 13:36:40 0 [ERROR] WSREP: Only binlog_format= 'ROW' is currently supported. Configured value: 'MIXED'. Please adjust your configuration.
Apr 15 13:36:40 HOSTNAME sh[646241]: 2024-04-15 13:36:40 0 [ERROR] Aborting'
Apr 15 13:36:40 HOSTNAME systemd[1]: mariadb.service: Control process exited, code=exited, status=1/FAILURE
```

The default `binlog_format` for MariaDB is `MIXED` (>= [MariaDB 10.2.4](https://mariadb.com/kb/en/mariadb-1024-release-notes/)) / `STATEMENT` (<= [MariaDB 10.2.3](https://mariadb.com/kb/en/mariadb-1023-release-notes/)).

Cheers
Thomas

**Comment by fraenki** [comment]
Apologies. The CI pipeline was not running, so this went unnoticed... :facepalm:

**Comment by fraenki** [comment]
Fixed in `main` and [CI](https://github.com/markt-de/puppet-galera/actions/runs/8767894570) done. Will be included in next release.
